#!/bin/bash

io="../src/utils/io/io.cpp"

eikonal_model="../src/model/eikonal/eikonal_model.cpp"
scalar_model="../src/model/scalar/scalar_model.cpp"
acoustic_model="../src/model/acoustic/acoustic_model.cpp"
elastic_model="../src/model/elastic/elastic_model.cpp"

geometry="../src/geometry/geometry.cpp"
regular_geom="../src/geometry/regular/regular.cpp"
streamer_geom="../src/geometry/streamer/streamer.cpp"

gaussian_1st="../src/wavelet/gaussian_1st/gaussian_1st.cpp"
gaussian_2nd="../src/wavelet/gaussian_2nd/gaussian_2nd.cpp"

modeling="../src/modeling/modeling.cpp"
eikonal_modeling="../src/modeling/eikonal/eikonal_modeling.cpp"
scalar_modeling="../src/modeling/scalar/scalar_modeling.cpp"
acoustic_modeling="../src/modeling/acoustic/acoustic_modeling.cpp"
elastic_modeling="../src/modeling/elastic/elastic_modeling.cpp"

main="../src/modeling_main.cpp"

flags="-fopenmp -lm -O3"

USER_MESSAGE="
Usage:
    $ $0 -help       # to see the keys allowed
    $ $0 -model      # to build a layer cake model 
    $ $0 -compile    # to compile all programs          
    $ $0 -run        # to run seismic modeling 

Please, follow the expecifications from parameters.txt file    
"
# Check if user provide some parameter
[ -z "$1" ] && {
	echo " "
	echo "You didn't provide any parameter!" 
	echo "Type $0 -help for more info"
	echo " "  
	exit 1 
}

case "$1" in

-help ) 
	echo -e "$USER_MESSAGE"
	exit 0
;;

-model) 

    python3 ../src/utils/py_codes/build_model.py parameters.txt

	exit 0
;;

-compile) 

    echo -e "Compiling the stand-alone executable!"

    echo -e "\n../bin/\033[31mmodeling.exe\033[m \n" 
    g++ $flags $io $eikonal_model $scalar_model $acoustic_model $elastic_model $gaussian_1st $gaussian_2nd $geometry $regular_geom $streamer_geom $modeling $eikonal_modeling $scalar_modeling $acoustic_modeling $elastic_modeling $main -o ../bin/modeling.exe
    
	exit 0
;;

-run) 
    
    ./../bin/modeling.exe parameters.txt

	exit 0
;;

* ) ## Message for bad parameter
	
	echo -e "\033[31mERRO: Option $1 unknown!\033[m"
	echo -e "\033[31mType $0 -h for help \033[m"
	exit 3
;;

esac
